//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmaHarjoitus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektitEntities : DbContext
    {
        public ProjektitEntities()
            : base("name=ProjektitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Henkilo> Henkilo { get; set; }
        public virtual DbSet<Projekti> Projekti { get; set; }
        public virtual DbSet<Tunti> Tunti { get; set; }
    }
}
